theme: minima
title: My Blog
author: Marco Krause
email: Marco.Krause7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Why I want to be an engineer.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
